### ISSUE TITLE
Do you have a command line that copy a folder and all subfolders from one account to another

### ISSUE THREAD

**Issue by Palazzia** [taers232c/GAMADV-X#22]
FYI,
I need to duplicate an account because it has a lot of files owned by non company account and I can't transfer the ownership, in theory if you have a command that copy all the content of accountA into AccountB, will be even better.

But considering that all the file that I need are into a specific folder, do you have a command line that will copy all these file from folder XXX accountA to folder XXX accountB

Please be aware that this account folder has 750.000 files for a total of 2.5 T.B., could be good also to have an estimate of time.

waiting for your help kind regards

AP

**Comment by taers232c** [comment]
AP,

https://github.com/taers232c/GAMADV-X/wiki/Users---Drive---Transfer <https://github.com/taers232c/GAMADV-X/wiki/Users---Drive---Transfer>

Ross
--
ross.scroggs@gmail.com

**Comment by Palazzia** [comment]
Hi Ross,
Really thank you.... if you don’t mind you know I’m not an expert... could be possible to have 2/3 command line examples?

One to copy all the data from one account to another

A second one to copy a specific user folder (with the respective sub folders and files) to another account folder (again keeping the folder structure)

I don’t care about security ... I want to copy everything to a different account to escape from the google limitation of claiming ownership of other gmail domain .

Do you will be able to help me.

I have  to run that command on an account folder that has 750.000 for 2.5 T.B. Where the files are owned by 1000 of external people.

Kind regards

AP

PS how much time could take it the copy of a so large account?

Get Outlook for iOS<https://aka.ms/o0ukef>
________________________________

**Comment by Palazzia** [comment]
Dear Ross,
Really thanks to you.... I need to duplicate a google drive account of 2.5 T.B. Into a new one. I need it because the 30% of the data I owned by external gmail accounts. I need to duplicate/copy to a new account to reconcile data and ownership.... I don’t care about security.... I’m going to share again the data later and monitor external people.

Please how I can do it?

Do you have a gam command line and which is the best way to made the transfer quick?

Kind regards

AP

Get Outlook for iOS<https://aka.ms/o0ukef>
________________________________

**Comment by taers232c** [comment]
AP,

I'm working with another user trying to copy 200,000 files. We are discovering Google problems and are working around them.
It will not be quick, he estimates 2.5 days to do 200,000 files.
The gam transfer drive command only transfers files owned by accounta, I'll have to look into doing the transfer for all owners.
For a transfer of this size, you may want to talk to Google to see if they have a better method.

Ross
--
ross.scroggs@gmail.com

**Comment by Palazzia** [comment]
Hi Ross,
Here we have 750000 files 10 days for me could be fine... but I don’t want transfer data... I want to copy data like

FolderIdA accountA has to be copied into folderIdB accountB... i don’t care about security.. Like this everything will be owned by the new account.

Kind regards

AP

Get Outlook for iOS<https://aka.ms/o0ukef>
________________________________

**Comment by jmealo** [comment]
@Palazzia @taers232c Did you find a resolution for this issue?

If there's no way to do this using an OAuth token for the user who owns the files, you could always use Google Cloud Functions to do the transfer (one file per request, for large files, perhaps multi-part). I'm wondering if there's a way to accomplish a large "drive copy" on GCE's free tier. If you use block storage or object storage as an intermediate/scratch disk it seems like it should be possible, performant and if transfer to Google services (including Drive) are zero-rated the most cost effective solution assuming you need to download/upload rather than transfer ownership.

Just a thought, if there's frequent issues with these large transfers it might be better to take a slow/steady approach. Using the pub/sub API it'd be pretty trivial to show progress and verify success without issuing any API calls on behalf of the user which would count towards your Request Limit.
